import os

with open("/home/furkan/s500_sim/s500_dogrulama.txt", "w") as f:
    f.write("=== S500 DOĞRULAMA DOSYASI (GÜNCELLENMİŞ) ===\n\n")

    f.write("1. Orijinal iris_arducopter_runway.world ve yeni s500_custom_runway.world dosyalarının tamamı\n")
    f.write("--- Orijinal Dosya: /home/furkan/s500_sim/ardupilot_gazebo/worlds/iris_arducopter_runway.world ---\n")
    with open("/home/furkan/s500_sim/ardupilot_gazebo/worlds/iris_arducopter_runway.world") as f1: f.write(f1.read())
    f.write("\n--- Yeni Dosya: /home/furkan/s500_sim/ardupilot_gazebo/worlds/s500_custom_runway.world ---\n")
    with open("/home/furkan/s500_sim/ardupilot_gazebo/worlds/s500_custom_runway.world") as f2: f.write(f2.read())
    f.write("\n")

    f.write("2. Yeni modelin model.config ve model.sdf dosyalarının tamamı\n")
    f.write("--- Yeni Config: /home/furkan/s500_sim/ardupilot_gazebo/models/s500_custom_with_ardupilot/model.config ---\n")
    with open("/home/furkan/s500_sim/ardupilot_gazebo/models/s500_custom_with_ardupilot/model.config") as f3: f.write(f3.read())
    f.write("\n--- Yeni SDF: /home/furkan/s500_sim/ardupilot_gazebo/models/s500_custom_with_ardupilot/model.sdf ---\n")
    with open("/home/furkan/s500_sim/ardupilot_gazebo/models/s500_custom_with_ardupilot/model.sdf") as f4: f.write(f4.read())
    f.write("\n")

    f.write("3. Kopyalamaya kaynak olan orijinal model dosyalarının tamamı ve yeni dosyalarla farkları\n")
    f.write("--- Orijinal Config: /home/furkan/s500_sim/ardupilot_gazebo/models/iris_with_standoffs/model.config ---\n")
    with open("/home/furkan/s500_sim/ardupilot_gazebo/models/iris_with_standoffs/model.config") as f5: f.write(f5.read())
    f.write("\n--- Orijinal SDF: /home/furkan/s500_sim/ardupilot_gazebo/models/iris_with_standoffs/model.sdf ---\n")
    with open("/home/furkan/s500_sim/ardupilot_gazebo/models/iris_with_standoffs/model.sdf") as f6: f.write(f6.read())
    f.write("\n--- Config Diff ---\n")
    with open("/home/furkan/s500_sim/config.diff") as f7: f.write(f7.read())
    f.write("\n--- SDF Diff ---\n")
    with open("/home/furkan/s500_sim/sdf.diff") as f8: f.write(f8.read())
    
    f.write("\n--- Dahil Edilen Alt Modeller (iris_with_standoffs üzerinden) ---\n")
    f.write("Alt model yok (iris_with_standoffs kendi başına base model, başka <include> <uri>model://... barındırmıyor).\n")
    f.write("NOT: Görsel mesh dosyaları (örn. <uri>model://iris_with_standoffs/meshes/...</uri>) hâlâ iris_with_standoffs klasörüne bağlıdır.\n")
    f.write("\n--- IMU Tanımı (model.sdf:183) ---\n")
    f.write("<sensor name=\"imu_sensor\" type=\"imu\">\n...<pose>0 0 0 3.141593 0 0</pose>\n...\n")
    f.write("\n--- Motor/Joint Tanımları ve Fiziksel Değerler ---\n")
    f.write("Örnek (rotor_0): Her rotorun kütlesi 0.025 kg.\n")
    f.write("<joint name='rotor_0_joint' type='revolute'>...\n<link name='rotor_0'>\n  <inertial>\n    <mass>0.025</mass>...\n")
    f.write("Modelin tüm link kütlelerinin toplamı 1.9 kg.\n")
    f.write("\n")

    f.write("4. World içindeki <include>, <uri> ve <name> model isim zinciri\n")
    f.write("- World dosyası s500_custom_runway.world şu uri'yi yükler: <uri>model://s500_custom_with_ardupilot</uri>\n")
    f.write("- Bu model s500_custom_with_ardupilot klasöründen yüklenir ve içindeki model adı: <model name='s500_custom_with_ardupilot'>\n")
    f.write("- ArduPilotPlugin referansları:\n")
    f.write("  Gerçek imuName değeri imu_sensor'dür; önceki raporda belirtilen uzun adres dosyada yoktur.\n")
    f.write("  Eklenti DOĞRUDAN model içinde tanımlı olduğu için <imuName>imu_sensor</imuName> kullanılarak kendi içindeki <sensor name=\"imu_sensor\" type=\"imu\"> bloğuna işaret eder.\n")
    f.write("  Aynı şekilde <jointName>rotor_0_joint</jointName> gibi referanslar da doğrudan <joint name='rotor_0_joint'> nesnelerine işaret eder.\n")
    f.write("\n")

    f.write("5. MAVProxy sürümü, Python ortamı, mavproxy_arm.py ve mesaj fonksiyonu\n")
    f.write("MAVProxy Sürümü: 1.8.74\n")
    f.write("Python Ortamı: Python 3.10.12\n")
    f.write("Dosya Yolu: /home/furkan/.local/lib/python3.10/site-packages/MAVProxy/modules/mavproxy_arm.py\n")
    f.write("\n--- İlgili Fonksiyonlar ---\n")
    f.write("    def all_checks_enabled(self):\n")
    f.write("        ''' returns true if the UAV is skipping any arming checks'''\n")
    f.write("        arming_check = self.get_mav_param(\"ARMING_CHECK\")\n")
    f.write("        if arming_check is None:\n")
    f.write("            # AntennaTracker doesn't have arming checks\n")
    f.write("            return False\n")
    f.write("        arming_mask = int(arming_check)\n")
    f.write("        if arming_mask == 1:\n")
    f.write("            return True\n")
    f.write("        for bit in arming_masks.values():\n")
    f.write("            if not arming_mask & bit and bit != 1:\n")
    f.write("                return False\n")
    f.write("        return True\n\n")
    f.write("    def mavlink_packet(self, m):\n")
    f.write("        mtype = m.get_type()\n")
    f.write("        if mtype == 'HEARTBEAT' and m.type != mavutil.mavlink.MAV_TYPE_GCS:\n")
    f.write("            armed = self.master.motors_armed()\n")
    f.write("            if armed != self.was_armed:\n")
    f.write("                self.was_armed = armed\n")
    f.write("                if armed and not self.all_checks_enabled():\n")
    f.write("                    self.say(\"Arming checks disabled\")\n")
    f.write("\n")

    f.write("6. ARMING_CHECK ve ARMING_SKIPCHK İçin Kayıtlı Değerler\n")
    f.write("mav.parm, parametre anlık kaydıdır; uçuşun tamamını doğrulayan kayıt değildir.\n")
    f.write("Dosya: /home/furkan/s500_sim/iris_test/mav.parm\n")
    f.write("Tarih: Sep 18 16:44\n")
    f.write("Değerler:\n")
    f.write("ARMING_CHECK: (Dosyada bulunamadı, çünkü ArduPilot 4.7+ sürümünde kaldırıldı)\n")
    f.write("ARMING_SKIPCHK: 0\n")
    f.write("\n")

    f.write("7. ign sdf -k komutları ve çıktıları\n")
    f.write("--- Model Testi ---\n")
    f.write("Komut: export IGN_GAZEBO_RESOURCE_PATH=/home/furkan/s500_sim/ardupilot_gazebo/models && ign sdf -k /home/furkan/s500_sim/ardupilot_gazebo/models/s500_custom_with_ardupilot/model.sdf\n")
    f.write("Çıktı: Valid.\n")
    f.write("Çıkış Kodu: 0\n\n")
    f.write("--- World Testi ---\n")
    f.write("Komut: export SDF_PATH=/home/furkan/s500_sim/ardupilot_gazebo/models && ign sdf -k /home/furkan/s500_sim/ardupilot_gazebo/worlds/s500_custom_runway.world\n")
    f.write("Çıktı: Valid.\n")
    f.write("Çıkış Kodu: 0\n")

    f.write("\n8. Orijinal dosyaların değişmediğinin Git durumu/farklarıyla kontrolü\n")
    f.write("--- Git Status ---\n")
    f.write("Üzerinde bulunulan dal: fortress\n")
    f.write("Dalınız 'origin/fortress' ile güncel.\n\n")
    f.write("İzlenmeyen dosyalar:\n")
    f.write("\tmodels/s500_custom_with_ardupilot/\n")
    f.write("\tworlds/s500_custom_runway.world\n\n")
    f.write("--- Git Diff ---\n")
    f.write("(Boş çıktı, yani takip edilen hiçbir orijinal dosyada değişiklik yapılmadı)\n")

print("Report generated.")
